<?php
$pageTitle='Admin Dashboard'; include 'header.php'; requireAdmin();
function redirectAdmin(): void { header('Location: admin_dashboard.php'); exit(); }
if(isset($_GET['verify_user'])){ $id=(int)$_GET['verify_user']; $stmt=$woodDb->prepare('UPDATE tblUser SET is_verified=1 WHERE user_id=?'); $stmt->bind_param('i',$id); $stmt->execute(); flash('User verified.'); redirectAdmin(); }
if(isset($_GET['approve_seller'])){ $id=(int)$_GET['approve_seller']; $stmt=$woodDb->prepare("UPDATE tblUser SET is_verified=1, seller_status='approved' WHERE user_id=? AND role='seller'"); $stmt->bind_param('i',$id); $stmt->execute(); flash('Seller approved.'); redirectAdmin(); }
if(isset($_GET['reject_seller'])){ $id=(int)$_GET['reject_seller']; $stmt=$woodDb->prepare("UPDATE tblUser SET seller_status='rejected' WHERE user_id=? AND role='seller'"); $stmt->bind_param('i',$id); $stmt->execute(); flash('Seller rejected.'); redirectAdmin(); }
if(isset($_GET['approve_product'])){ $id=(int)$_GET['approve_product']; $stmt=$woodDb->prepare('UPDATE tblProduct SET admin_approved=1 WHERE product_id=?'); $stmt->bind_param('i',$id); $stmt->execute(); flash('Product approved.'); redirectAdmin(); }
if(isset($_GET['reject_product'])){ $id=(int)$_GET['reject_product']; $stmt=$woodDb->prepare('DELETE FROM tblProduct WHERE product_id=?'); $stmt->bind_param('i',$id); $stmt->execute(); flash('Product rejected/removed.'); redirectAdmin(); }
if(isset($_GET['mark_sold'])){ $id=(int)$_GET['mark_sold']; $stmt=$woodDb->prepare("UPDATE tblProduct SET status='sold' WHERE product_id=?"); $stmt->bind_param('i',$id); $stmt->execute(); flash('Product marked sold.'); redirectAdmin(); }
if(isset($_GET['delete_user'])){ $id=(int)$_GET['delete_user']; $stmt=$woodDb->prepare("DELETE FROM tblUser WHERE user_id=? AND role <> 'admin'"); $stmt->bind_param('i',$id); $stmt->execute(); flash('User deleted.'); redirectAdmin(); }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['add_user'])){ $name=cleanInput($_POST['name']); $email=cleanInput($_POST['email']); $username=cleanInput($_POST['username']); $role=$_POST['role']; $hash=password_hash($_POST['password'], PASSWORD_DEFAULT); $sellerStatus=$role==='seller'?'approved':'none'; $stmt=$woodDb->prepare('INSERT INTO tblUser(name,email,username,password,role,is_verified,seller_status) VALUES(?,?,?,?,?,1,?)'); $stmt->bind_param('ssssss',$name,$email,$username,$hash,$role,$sellerStatus); $stmt->execute(); flash('User added.'); redirectAdmin(); }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['update_user'])){ $id=(int)$_POST['user_id']; $name=cleanInput($_POST['name']); $email=cleanInput($_POST['email']); $role=$_POST['role']; $stmt=$woodDb->prepare("UPDATE tblUser SET name=?, email=?, role=? WHERE user_id=? AND role <> 'admin'"); $stmt->bind_param('sssi',$name,$email,$role,$id); $stmt->execute(); flash('User updated.'); redirectAdmin(); }
$users=$woodDb->query('SELECT * FROM tblUser ORDER BY created_at DESC');
$products=$woodDb->query('SELECT p.*, u.name AS seller_name FROM tblProduct p JOIN tblUser u ON p.seller_id=u.user_id ORDER BY p.admin_approved, p.created_at DESC');
$orders=$woodDb->query('SELECT o.*, u.name AS user_name FROM tblOrder o JOIN tblUser u ON o.user_id=u.user_id ORDER BY o.order_date DESC');
$stats=$woodDb->query("SELECT (SELECT COUNT(*) FROM tblUser WHERE is_verified=0) pending_users,(SELECT COUNT(*) FROM tblUser WHERE role='seller' AND seller_status='pending') pending_sellers,(SELECT COUNT(*) FROM tblProduct WHERE admin_approved=0) pending_products,(SELECT COUNT(*) FROM tblOrder) orders")->fetch_assoc();
?>
<section class="dashboard-hero admin"><div><span class="eyebrow">Admin Control Room</span><h1>Pastimes moderation</h1><p>Approve users, sellers, and products before they move through the store.</p></div><a class="btn ghost" href="shop.php">View Store</a></section>
<div class="grid four"><div class="stat-card"><strong><?php echo $stats['pending_users']; ?></strong><span>Pending users</span></div><div class="stat-card"><strong><?php echo $stats['pending_sellers']; ?></strong><span>Pending sellers</span></div><div class="stat-card"><strong><?php echo $stats['pending_products']; ?></strong><span>Pending products</span></div><div class="stat-card"><strong><?php echo $stats['orders']; ?></strong><span>Orders</span></div></div>
<section class="panel"><h2>Users and verification</h2><div class="table-wrap"><table><tr><th>ID</th><th>Name</th><th>Email</th><th>Username</th><th>Role</th><th>Verified</th><th>Seller</th><th>Actions</th></tr><?php while($u=$users->fetch_assoc()): ?><tr><td><?php echo $u['user_id']; ?></td><td><?php echo e($u['name']); ?></td><td><?php echo e($u['email']); ?></td><td><?php echo e($u['username']); ?></td><td><span class="badge"><?php echo e($u['role']); ?></span></td><td><?php echo $u['is_verified']?'Yes':'Pending'; ?></td><td><?php echo e($u['seller_status']); ?></td><td class="actions"><?php if(!$u['is_verified'] && $u['role']!=='admin'): ?><a class="btn small success" href="?verify_user=<?php echo $u['user_id']; ?>">Verify</a><?php endif; ?><?php if($u['role']==='seller' && $u['seller_status']!=='approved'): ?><a class="btn small success" href="?approve_seller=<?php echo $u['user_id']; ?>">Approve Seller</a><?php endif; ?><?php if($u['role']==='seller' && $u['seller_status']!=='rejected'): ?><a class="btn small danger" href="?reject_seller=<?php echo $u['user_id']; ?>">Reject</a><?php endif; ?><?php if($u['role']!=='admin'): ?><a class="btn small danger" onclick="return confirmAction('Delete user?')" href="?delete_user=<?php echo $u['user_id']; ?>">Delete</a><?php endif; ?></td></tr><?php if($u['role']!=='admin'): ?><tr><td colspan="8"><form method="post" class="inline-edit"><input type="hidden" name="user_id" value="<?php echo $u['user_id']; ?>"><input name="name" value="<?php echo e($u['name']); ?>" required><input type="email" name="email" value="<?php echo e($u['email']); ?>" required><select name="role"><option value="buyer" <?php if($u['role']==='buyer') echo 'selected'; ?>>Buyer</option><option value="seller" <?php if($u['role']==='seller') echo 'selected'; ?>>Seller</option></select><button class="btn small" name="update_user">Update</button></form></td></tr><?php endif; ?><?php endwhile; ?></table></div></section>
<section class="panel"><h2>Add verified user</h2><form method="post" class="inline-edit add"><input name="name" placeholder="Name" required><input type="email" name="email" placeholder="Email" required><input name="username" placeholder="Username" required><input type="password" name="password" minlength="8" maxlength="8" placeholder="8-char password" required><select name="role"><option value="buyer">Buyer</option><option value="seller">Seller</option></select><button class="btn primary" name="add_user">Add User</button></form></section>
<section class="panel"><h2>Product approval</h2><div class="table-wrap"><table><tr><th>Image</th><th>Code</th><th>Name</th><th>Seller</th><th>Price</th><th>Status</th><th>Approved</th><th>Actions</th></tr><?php while($p=$products->fetch_assoc()): ?><tr><td><img class="table-img" src="<?php echo e(productImage($p['image'])); ?>"></td><td><?php echo e($p['product_code']); ?></td><td><?php echo e($p['name']); ?></td><td><?php echo e($p['seller_name']); ?></td><td><?php echo formatRand($p['price']); ?></td><td><?php echo e($p['status']); ?></td><td><?php echo $p['admin_approved']?'Yes':'Pending'; ?></td><td class="actions"><?php if(!$p['admin_approved']): ?><a class="btn small success" href="?approve_product=<?php echo $p['product_id']; ?>">Approve</a><a class="btn small danger" href="?reject_product=<?php echo $p['product_id']; ?>">Reject</a><?php endif; ?><a class="btn small ghost" href="?mark_sold=<?php echo $p['product_id']; ?>">Mark Sold</a></td></tr><?php endwhile; ?></table></div></section>
<section class="panel"><h2>Orders and delivery follow-up</h2><div class="table-wrap"><table><tr><th>Order</th><th>Buyer</th><th>Delivery details</th><th>Total</th><th>Status</th><th>Date</th></tr><?php while($o=$orders->fetch_assoc()): ?><tr><td>#<?php echo $o['order_id']; ?></td><td><?php echo e($o['user_name']); ?></td><td><?php echo e($o['full_name'].', '.$o['address'].', '.$o['city'].', '.$o['postal_code'].', '.$o['phone']); ?></td><td><?php echo formatRand($o['total']); ?></td><td><?php echo e($o['status']); ?></td><td><?php echo e($o['order_date']); ?></td></tr><?php endwhile; ?></table></div></section>
<?php include 'footer.php'; ?>
