<?php
$pageTitle='Product'; include 'header.php';
$id=(int)($_GET['id'] ?? 0);
$stmt=$woodDb->prepare("SELECT p.*, u.name AS seller_name, u.user_id AS seller_user_id FROM tblProduct p JOIN tblUser u ON p.seller_id=u.user_id WHERE p.product_id=? AND p.admin_approved=1");
$stmt->bind_param('i',$id); $stmt->execute(); $p=$stmt->get_result()->fetch_assoc();
if(!$p){ echo '<div class="empty-state">Product not found.</div>'; include 'footer.php'; exit(); }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['add_cart'])){ requireLogin(); if(($_SESSION['role']??'')!=='buyer'){ flash('Only buyers can add items to cart.','error'); header('Location: product.php?id='.$id); exit(); } $uid=(int)$_SESSION['user_id']; $stmt=$woodDb->prepare('INSERT INTO tblCart(user_id,product_id,quantity) VALUES(?,?,1) ON DUPLICATE KEY UPDATE quantity=quantity+1'); $stmt->bind_param('ii',$uid,$id); $stmt->execute(); flash('Item added to cart.'); header('Location: cart.php'); exit(); }
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['send_message'])){ requireLogin(); if(($_SESSION['role']??'')!=='buyer'){ flash('Only buyers can message sellers from product pages.','error'); header('Location: product.php?id='.$id); exit(); } $msg=cleanInput($_POST['message_text'] ?? ''); if($msg!==''){ $buyer=(int)$_SESSION['user_id']; $seller=(int)$p['seller_id']; $stmt=$woodDb->prepare('INSERT INTO tblMessage(product_id,buyer_id,seller_id,sender_id,message_text) VALUES(?,?,?,?,?)'); $stmt->bind_param('iiiis',$id,$buyer,$seller,$buyer,$msg); $stmt->execute(); flash('Message sent to seller.'); } header('Location: messages.php?product_id='.$id); exit(); }
?>
<section class="product-detail"><div class="detail-image"><img src="<?php echo e(productImage($p['image'])); ?>" alt="<?php echo e($p['name']); ?>"></div><div class="detail-copy"><span class="badge"><?php echo e($p['product_code']); ?></span><h1><?php echo e($p['name']); ?></h1><p class="price-big"><?php echo formatRand($p['price']); ?></p><p><?php echo e($p['description']); ?></p><div class="meta-grid"><span><strong>Brand</strong><?php echo e($p['brand']); ?></span><span><strong>Category</strong><?php echo e($p['category']); ?></span><span><strong>Size</strong><?php echo e($p['size']); ?></span><span><strong>Condition</strong><?php echo e($p['item_condition']); ?></span><span><strong>Seller</strong><?php echo e($p['seller_name']); ?></span></div><form method="post" class="inline-actions"><button class="btn primary" name="add_cart">Add to Cart</button></form><form method="post" class="message-box"><label>Message seller about this item</label><textarea name="message_text" rows="4" placeholder="Ask about fit, condition, delivery, etc." required></textarea><button class="btn ghost" name="send_message">Send Message</button></form></div></section>
<?php include 'footer.php'; ?>
